name: Run Tests

on:
  pull_request:
    branches: [master, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install && npm install lerna -g
      - name: Build dependencies
        run: lerna bootstrap --hoist --ci && npm run build
        env:
          NACELLE_SPACE_ID: ${{ secrets.NACELLE_SPACE_ID }}
          NACELLE_GRAPHQL_TOKEN: ${{ secrets.NACELLE_GRAPHQL_TOKEN }}
          DASHBOARD_AUTH_TOKEN: ${{ secrets.DASHBOARD_AUTH_TOKEN }}
      - name: Bootstrap local Lerna dependencies
        run: lerna clean -y && lerna bootstrap --force-local --hoist --ci
      - name: Lint
        run: npm run lint
      - name: Tests with coverage report
        uses: ChristiaanScheermeijer/jest-reporter-action@v0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          test-command: 'npm run test:ci'
